### ISSUE TITLE
Drones disregarding energy settings

### ISSUE THREAD

**Issue by alexanderwalters89** [GreyHak/dsp-drone-clearing#2] opened 2021-02-22 23:39 UTC
Drones don't seem to pay attention to the energy settings at all.

I spin up a new game, set the energy restriction fairly high (0.9)... and they promptly use up all my energy very quickly.

I switch over to my previous almost-done run and yep, they start new tasks at less than 90% it's not just that they're only checking when adding to the queue.

Only giving build orders (or going airborne) seems to make them stop.

Also I can't figure out what precisely causes them to start back up - I never did get them to restart on the new game without save/load but takeoff/landing did it when loading the old game.

**Comment by GreyHak** [comment] 2021-02-23 00:17
@alexanderwalters89 Thank you for the feedback.  I'll look into it.  I never tested with percent as high as 0.9.  I'm working on an feature fix to add an enable/disable toggle that I'm almost done with.  So you might see a release before I get to your report.

**Comment by alexanderwalters89** [comment] 2021-02-23 00:31
Thanks.

Did some more testing and it seems to be behaving itself as long as I save, then load.

I can't reproduce the behaviour outside of a brand new game.

The issue with the late-stage game seems to have been caused by me changing the range rather than power conserve setting.

Enable-disable is perfect, by the way.

Especially if it force-recalls the drones.

**Comment by GreyHak** [comment] 2021-02-23 01:19
Problem reproduced.

**Comment by GreyHak** [comment] 2021-02-23 01:25
The logic for stopping based on energy levels is good.  The problem is caused by too many tasks getting queued up, way more than drones to service them.

**Comment by GreyHak** [comment] 2021-02-23 01:55
@alexanderwalters89 Issue should be fixed in release v1.2.1

**Closed** 2021-02-23 01:56 UTC
Labels: bug
