### ISSUE TITLE
Compatibility Issue with mod "Render Distance"

### ISSUE THREAD

**Issue by cdeath-zz** [GreyHak/dsp-drone-clearing#5] opened 2021-02-24 05:31 UTC
So the mod Render Distance teleports an invisible copy of Icarus to other planets so you can see the details of those planets up close as if you were there.  However if the drones are enabled, they attempt to harvest resources and it is causing errors in the game.  I'm not sure if this is fixable so for now I will make sure I have the drone collection turned off when looking at other planets.  Wanted to give you a heads up on this.  Also let me know if you want a copy of those errors I can SS them for you.

**Comment by GreyHak** [comment] 2021-02-24 15:17
Thank you for the report @cdeath-zz .  I'll try testing with the Render Distance mod this evening, and see if I can reproduce your problem.

**Comment by GreyHak** [comment] 2021-02-25 04:34
I've tested with RenderDistance v0.6.1, and reproduced exception.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DSP_RenderDistance.DSP_RenderDistance.patch_OnPlanetClick (UIStarmap,UIStarmapPlanet) <0x00090>
(wrapper dynamic-method) UIStarmap.DMD<UIStarmap..OnPlanetClick> (UIStarmap,UIStarmapPlanet) <0x000d7>
UIStarmap.OnScreenClick (UnityEngine.EventSystems.BaseEventData) <0x000d2>
UnityEngine.Events.InvokableCall`1<UnityEngine.EventSystems.BaseEventData>.Invoke (UnityEngine.EventSystems.BaseEventData) <0x00048>
UnityEngine.Events.UnityEvent`1.Invoke (T0) <0x000dc>
UnityEngine.EventSystems.EventTrigger.Execute (UnityEngine.EventSystems.EventTriggerType,UnityEngine.EventSystems.BaseEventData) <0x000b6>
UnityEngine.EventSystems.EventTrigger.OnPointerDown (UnityEngine.EventSystems.PointerEventData) <0x00029>
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerDownHandler,UnityEngine.EventSystems.BaseEventData) <0x0004f>
UnityEngine.EventSystems.ExecuteEvents.Execute<UnityEngine.EventSystems.IPointerDownHandler> (UnityEngine.GameObject,UnityEngine.EventSystems.BaseEventData,UnityEngine.EventSystems.ExecuteEvents/EventFunction`1<UnityEngine.EventSystems.IPointerDownHandler>) <0x0034d>
UnityEngine.EventSystems.EventSystem:Update()

**Comment by cdeath-zz** [comment] 2021-02-25 04:54
That looks like the same one I was just able to get just now.  However, that is NOT the one I originally got.  It was specifically calling out your mod in the exception, dang I should have screenshot it.

**Comment by GreyHak** [comment] 2021-02-25 04:55
@cdeath-zz I reproduced the exception in RenderDistance v0.6.1 without any other mods installed.  I believe this isn't a problem with the Drone Cleaning mod.

**Comment by GreyHak** [comment] 2021-02-25 05:08
@cdeath-zz The problem I found is apparently not the problem you were referring to.  The problem is the an invisible mecha launches drones while remotely teleported, not the exception.  I've reported the exception to the Render Distance GitHub: https://github.com/sp00ktober/DSP_Mod/issues/5

**Comment by cdeath-zz** [comment] 2021-02-25 05:13
Yeah, there was some sort of error and I saw **drone** in the exception, and like a dummy I didn't screenshot it and now I can't replicate it.  Yeah the teleporting mech is how that mod lets you view other planets as if you were there.

**Comment by cdeath-zz** [comment] 2021-02-25 05:30
Maybe I'm mis-remembering the issue and this error I got just now is the one that I got, because it's not the same one you got there.

NullReferenceException: Object reference not set to an instance of an object
at RaycastLogic.GameTick () <0x031c0>
at PlanetPhysics.GameTick () <0x00045>
at (wrapper dynamic-method) GameData.DMD<GameData..GameTick> (GameData,long) <0x000a4>
at GameMain.FixedUpdate () <0x0025f>

It seems to be related to when the drones harvest on the remote planet and you mouse over a rock that they harvest.  The game isn't updating the rock so the rock is supposed to be gone.  I'm going to keep trying to replicate the other error because I swear I got one mentioning drones at the very least.

**Comment by cdeath-zz** [comment] 2021-02-25 05:38
GOT IT
NullReferenceException: Object reference not set to an instance of an object
at DysonSphereDroneClearing.DysonSphereDroneClearing/DroneAction_Mine.DroneGameTick () <0x0015d>
at DysonSphereDroneClearing.DysonSphereDroneClearing.PlanetFactory_GameTick_Postfix (long) <0x00425>
at (wrapper dynamic-method) PlanetFactory.DMD<PlanetFactory..GameTick> (PlanetFactory,long) <0x00221>
at (wrapper dynamic-method) GameData.DMD<GameData..GameTick> (GameData,long) <0x00282>
at GameMain.FixedUpdate () <0x0025f>

It has something to do with the drones being active and then opening the planet view and moving to a remote planet.  I kept messing with it and eventually got this while the drones were harvesting / returning / going out.

**Comment by GreyHak** [comment] 2021-02-25 16:55
@cdeath-zz Thank you for the extra detail.  It's an easy fix to disable drone clearing when Render Distance puts the invisible Icarus on another planet.  That will prevent the weird drone-clearing-from-a-distance effect.  I'll look into the DroneGameTick bugs this evening.

**Comment by GreyHak** [comment] 2021-02-25 20:31
@cdeath-zz v1.2.4 should fix two of the three issues discussed in this report chain.  I haven't seen the IndexOutOfRangeException.  Hopefully that's because the issue was fixed by one of the other fixes.  Please let me know if you're having any more problems with v1.2.4.  Thank you.

**Comment by cdeath-zz** [comment] 2021-02-25 22:05
So far so good.  I tried hard to cause problems doing all kinds of things and no errors.

**Comment by GreyHak** [comment] 2021-02-26 02:47
Great to hear.  Thank you.

**Closed by GreyHak** 2021-02-26 02:47 UTC
Labels: bug, enhancement
