### ISSUE TITLE
drones seem to have a new "do it when I feel like it" setting

### ISSUE THREAD

**Issue by cdeath-zz** [GreyHak/dsp-drone-clearing#4] opened 2021-02-24 05:16 UTC
So I really have no explanation as to why the drones randomly decide whether they will collect resources or not.  First loading up, they immediately get to work and cleared up the nearby resources.  I walked back to my base (that was already cleared) but then I moved away and they refused to collect more.  Then I moved somewhere else and they started collecting again.  Then back to my base and elsewhere they refused again.  It seems totally random when they will collect.  Toggling on and off collection has no effect except when they are working correctly it does make them cancel collection.
edit ---
Forgot to mention, I did have more than 10 empty spaces and  almost full power

**Comment by GreyHak** [comment] 2021-02-24 15:15
Thank you for the report @cdeath-zz .  I'm unsure what is causing your problem.  It sounds like the drones are limiting power usage, but you've indicated yours is almost full.  I've been thinking about a configuration flag to enable debug messages.  If I release an update which allows you to enable messages explaining why drones aren't clearing, would you be able to work with me and the logs to figure this out?

**Comment by cdeath-zz** [comment] 2021-02-24 16:18
Yea sure, I like having this ability and it saves a TON of time!

**Comment by GreyHak** [comment] 2021-02-25 04:00
@cdeath-zz I've added the debug config flag to v1.2.3.  This should give us enough information to determine why you're drones aren't clearing.

**Comment by cdeath-zz** [comment] 2021-02-25 04:06
so of course now it won't do it.  Well, before I wasn't trying so I will play normally and see if I can catch it and post it here.  What log file will that save to?

**Comment by cdeath-zz** [comment] 2021-02-25 04:35
Update
[Info   :DSP Drone Clearing] 4 active clearing drones. 0 active missions.
[Info   :DSP Drone Clearing] Skipping due to number of drone assignments: configMaxClearingDroneCount=256, player.mecha.droneCount=4, player.mecha.idleDroneCount=4

I built something, then while drones were out (only 2) I moved in range of trees, the drones were completely unresponsive to clearing trees and rocks from then onward.

**Comment by newt111** [comment] 2021-02-25 21:39
I'm using 1.2.4, and am having this same issue. I started walking toward some trees and rock to place a few power poles, the drones start collecting trees and such but after queuing and placing the buildings the drones never resumed clearing resources. At the end of this log I'm standing in the middle of some trees and rocks with the drones doing nothing
[LogOutput.log](https://github.com/GreyHak/dsp-drone-clearing/files/6045888/LogOutput.log)

**Comment by GreyHak** [comment] 2021-02-26 00:22
@newt111 Thank you for the report.  It helped knowing that there were more people seeing the problem.
@cdeath-zz I've reproduced a similar sounding problem (without any other mods installed), but it doesn't sound exactly the same.  The mod queues up tasks for the game to assign to the drones.  They're getting queued, but it looks like they aren't getting assigned.  I'll try to fix it tonight; top priority.

**Comment by GreyHak** [comment] 2021-02-26 02:46
@cdeath-zz and @newt111 Thank you both for sticking with me on this one.  I can't believe I didn't find this myself during test.  I really appreciate your help!!!  This should now be fixed in v1.2.5.  It was a small fix.

**Closed by GreyHak** 2021-02-26 02:46 UTC
Labels: bug

**Comment by cdeath-zz** [comment] 2021-02-26 04:22
Great job!  I tried my hardest to break it, but the drones powered through it.  Glad to help, this is an awesome QoL addition.
